---
# See https://github.com/jvautier/project-cli
fullname: jvautier/code-cli
description: Git repository utility
tags:
  - bash
  - cli
  - git
  - development
github:
  has_issues: true
  has_projects: false
  has_wiki: false
